# Generated by Django 4.0.1 on 2022-02-06 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
