# Generated by Django 4.0.1 on 2022-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wishlistitem_selected_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='tags',
        ),
        migrations.CreateModel(
            name='WishListItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(to='home.WishListItem')),
            ],
        ),
    ]
