# Generated by Django 4.0.1 on 2022-02-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_wishlistitem_tag_wishlistitemtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitemtag',
            name='tags',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='tags',
            field=models.ManyToManyField(to='home.WishListItemTag'),
        ),
        migrations.AddField(
            model_name='wishlistitemtag',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
