# Generated by Django 4.0.1 on 2022-02-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_wishlistitemtag_tags_wishlistitem_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListTagQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_tags', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wishlistitem')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.wishlistitemtag')),
            ],
        ),
    ]
