# Generated by Django 4.0.1 on 2022-02-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_wishlisttagquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='tags',
            field=models.ManyToManyField(through='home.WishListTagQuantity', to='home.WishListItemTag'),
        )
    ]
