# Generated by Django 4.0.1 on 2022-02-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_user_wishlistitem_username_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
    ]
