# Generated by Django 4.0.1 on 2022-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_usersettings_bio_usersettings_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='item_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='wishlist'),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='item_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
