# Generated by Django 4.0.1 on 2022-03-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_wishlistitem_item_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='store',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
